openapi: 3.0.3
info:
  title: Typescript DDD Skeleton
  description: |-
    Typescript DDD Basic Skeleton based on CodelyTV®
  version: 1.0.0
servers:
  - url: http://localhost:9000
    description: Local environment.
tags:
  - name: status
    description: Status of the system
paths:
  /status:
    get:
      tags:
        - status
      summary: Check the status of the systems
      responses:
        '200':
          description: Status ok
